/**
 * @file     stage_bridge.cpp
 * @brief    Compiler driver implementation
 *
 * @ingroup  Tool / polyc
 * @author   Manning Cyrus
 * @date     2026-04-10
 */
// ============================================================================
// stage_bridge.cpp — Stage 4 implementation
// ============================================================================

#include "tools/polyc/src/stage_bridge.h"

#include <filesystem>
#include <fstream>
#include <iostream>
#include <unordered_set>

#include "frontends/ploy/include/ploy_sema.h"
#include "tools/polyld/include/linker.h"
#include "tools/polyld/include/polyglot_linker.h"

namespace polyglot::tools {

BridgeResult RunBridgeStage(const DriverSettings &settings,
                             const MarshalResult &marshal,
                             const SemanticResult &semantic,
                             const std::string &aux_dir,
                             const std::string &stem) {
    BridgeResult result;
    const bool V = settings.verbose;

    // Non-.ploy or empty plan: no cross-language bridges needed.
    if (settings.language != "ploy" || !semantic.success) {
        result.success = true;
        return result;
    }

    // ── Build PolyglotLinker ─────────────────────────────────────────────────
    linker::LinkerConfig lnk_cfg;
    lnk_cfg.verbose = V;
    linker::PolyglotLinker poly_linker(lnk_cfg);

    // Register LINK entries from sema
    for (const auto &entry : semantic.link_entries) {
        poly_linker.AddLinkEntry(entry);
    }

    // Register symbols from link entries and marshal plan
    std::unordered_set<std::string> registered;
    auto register_sym = [&](const std::string &name, const std::string &language) {
        const std::string key = language + "::" + name;
        if (!registered.insert(key).second) return;

        linker::CrossLangSymbol sym;
        sym.name = name;
        sym.mangled_name = name;
        sym.language = language;
        sym.type = linker::SymbolType::kFunction;

        auto it = semantic.signatures.find(name);
        if (it != semantic.signatures.end() && it->second.param_count_known) {
            for (const auto &t : it->second.param_types) {
                linker::CrossLangSymbol::ParamDesc pd;
                pd.type_name = t.ToString();
                pd.size = 8;
                pd.is_pointer = t.IsPointer();
                sym.params.push_back(pd);
            }
            linker::CrossLangSymbol::ParamDesc rd;
            rd.type_name = it->second.return_type.ToString();
            rd.size = 8;
            rd.is_pointer = it->second.return_type.IsPointer();
            sym.return_desc = rd;
        }
        poly_linker.AddCrossLangSymbol(sym);
        if (V) std::cerr << "[stage/bridge]   sym " << language << "::" << name << "\n";
    };

    for (const auto &entry : semantic.link_entries) {
        register_sym(entry.target_symbol, entry.target_language);
        register_sym(entry.source_symbol, entry.source_language);
    }
    for (const auto &cp : marshal.call_plans) {
        register_sym(cp.target_function, cp.target_language);
        register_sym(cp.source_function, cp.source_language);
    }

    // ── Resolve ──────────────────────────────────────────────────────────────
    bool link_ok = poly_linker.ResolveLinks();
    if (!link_ok) {
        for (const auto &e : poly_linker.GetErrors()) {
            result.diagnostics.Report(
                core::SourceLoc{"<bridge>", 1, 1}, e);
        }
        if (!settings.force) {
            result.success = false;
            return result;
        }
        std::cerr << "[warn] continuing in --force mode despite bridge errors\n";
    }

    // ── Collect stubs ─────────────────────────────────────────────────────────
    for (const auto &stub : poly_linker.GetStubs()) {
        BridgeStubEntry entry;
        entry.stub_name   = stub.stub_name;
        entry.code        = stub.code;
        entry.relocations = stub.relocations;
        result.stubs.push_back(std::move(entry));
        if (V) {
            std::cerr << "[stage/bridge]   stub " << stub.stub_name
                      << " (" << stub.code.size() << " bytes)\n";
        }
    }

    // ── Serialize descriptor file ─────────────────────────────────────────────
    // Written as text (LINK / CALL / SYMBOL lines) so that polyld can consume
    // it directly via --ploy-desc without a separate binary parser.
    if (!aux_dir.empty()) {
        namespace fs = std::filesystem;
        fs::path desc_path =
            fs::path(aux_dir) / (stem + "_link_descriptors.paux");
        std::ofstream ofs(desc_path);
        if (ofs.is_open()) {
            ofs << "# PolyglotCompiler cross-language descriptor file\n";
            ofs << "# Generated by stage_bridge — do not edit manually\n";

            for (const auto &entry : semantic.link_entries) {
                ofs << "LINK " << entry.target_language
                    << " " << entry.source_language
                    << " " << entry.target_symbol
                    << " " << entry.source_symbol << "\n";
            }
            for (const auto &cp : marshal.call_plans) {
                std::string stub_name =
                    "__ploy_bridge_" + cp.target_language + "_" +
                    cp.source_language + "_" + cp.target_function;
                ofs << "CALL " << stub_name
                    << " " << cp.source_language
                    << " " << cp.target_language
                    << " " << cp.source_function
                    << " " << cp.target_function << "\n";
            }
            // Symbols
            std::unordered_set<std::string> seen;
            auto emit_sym = [&](const std::string &name, const std::string &lang) {
                if (!seen.insert(lang + "::" + name).second) return;
                ofs << "SYMBOL " << name << " " << lang << " " << name << "\n";
            };
            for (const auto &entry : semantic.link_entries) {
                emit_sym(entry.target_symbol, entry.target_language);
                emit_sym(entry.source_symbol, entry.source_language);
            }
            for (const auto &cp : marshal.call_plans) {
                emit_sym(cp.target_function, cp.target_language);
                emit_sym(cp.source_function, cp.source_language);
            }
            ofs.close();
            result.descriptor_file = desc_path.string();
            if (V) std::cerr << "[stage/bridge] descriptors -> "
                             << result.descriptor_file << "\n";
        }
    }

    result.success = true;
    return result;
}

}  // namespace polyglot::tools
