/**
 * @file     version.h
 * @brief    Shared definitions
 *
 * @ingroup  Common
 * @author   Manning Cyrus
 * @date     2026-04-10
 */
// ============================================================================
// version.h — Auto-generated by CMake.  DO NOT EDIT.
//
// Single source of truth for project identity and version constants.
// All tools, libraries, and UI components should #include this header
// instead of hard-coding version strings.
//
// To change the version, edit the top-level CMakeLists.txt:
//   project(PolyglotCompiler VERSION x.y.z ...)
// ============================================================================
#pragma once

/** @name Project identity */
/** @{ */
#define POLYGLOT_PROJECT_NAME      "PolyglotCompiler"
#define POLYGLOT_ORGANIZATION_NAME "PolyglotCompiler"
#define POLYGLOT_ORGANIZATION_DOMAIN "polyglotcompiler.org"

/** @} */

/** @name Semantic version components */
/** @{ */
#define POLYGLOT_VERSION_MAJOR 1
#define POLYGLOT_VERSION_MINOR 0
#define POLYGLOT_VERSION_PATCH 0
#define POLYGLOT_VERSION_STRING "1.0.0"

/** @} */

/** @name Derived convenience strings */
/** @{ */
#define POLYGLOT_VERSION_BANNER POLYGLOT_PROJECT_NAME " v" POLYGLOT_VERSION_STRING

/** @} */

/** @name Tool display names */
/** @{ */
#define POLYGLOT_POLYC_NAME   "polyc"
#define POLYGLOT_POLYLD_NAME  "polyld"
#define POLYGLOT_POLYASM_NAME "polyasm"
#define POLYGLOT_POLYOPT_NAME "polyopt"
#define POLYGLOT_POLYRT_NAME  "polyrt"
#define POLYGLOT_POLYTOPO_NAME "polytopo"
#define POLYGLOT_POLYBENCH_NAME "polybench"
#define POLYGLOT_POLYUI_NAME  "polyui"

/** @} */

/** @name IDE display strings */
/** @{ */
#define POLYGLOT_IDE_NAME   POLYGLOT_PROJECT_NAME " IDE"
#define POLYGLOT_IDE_BANNER POLYGLOT_POLYUI_NAME " (" POLYGLOT_IDE_NAME ") v" POLYGLOT_VERSION_STRING

/** @} */

/** @name Copyright */
/** @{ */
#define POLYGLOT_COPYRIGHT "Copyright (c) 2026 " POLYGLOT_PROJECT_NAME " Project"

/** @} */