/**
 * @file     object_lifecycle.cpp
 * @brief    Runtime implementation
 *
 * @ingroup  Runtime
 * @author   Manning Cyrus
 * @date     2026-04-10
 */
#include "runtime/include/interop/object_lifecycle.h"

#include <cstdlib>
#include <cstring>
#include <mutex>
#include <shared_mutex>
#include <vector>

#include "runtime/include/interop/container_marshal.h"
#include "runtime/include/interop/memory.h"
#include "runtime/include/libs/base.h"

namespace polyglot::runtime::interop {

// ============================================================================
// Language-specific destructor / cleanup bridges
// ============================================================================

void __ploy_py_del(void *object) {
    // For Python objects managed through the polyglot runtime, the object
    // pointer is a ForeignObject wrapper.  If the runtime was initialised
    // with a live CPython interpreter this would call Py_DECREF.  In the
    // stand-alone runtime we release the ForeignObject reference which
    // triggers its deleter (if any).
    if (!object) return;

    auto *fo = static_cast<ForeignObject *>(object);
    if (ForeignIsAlive(fo)) {
        ReleaseForeign(fo);
    }
}

void __ploy_cpp_delete(void *object) {
    // C++ objects allocated through NEW arrive here as ForeignObject wrappers
    // whose deleter invokes the destructor + operator delete.
    if (!object) return;

    auto *fo = static_cast<ForeignObject *>(object);
    if (ForeignIsAlive(fo)) {
        ReleaseForeign(fo);
    }
}

void __ploy_rust_drop(void *object) {
    // Rust objects with ownership transferred to the polyglot runtime are
    // wrapped in ForeignObject with a deleter that calls the Rust-side drop
    // glue (generated by the Rust backend).
    if (!object) return;

    auto *fo = static_cast<ForeignObject *>(object);
    if (ForeignIsAlive(fo)) {
        ReleaseForeign(fo);
    }
}

void __ploy_java_release(void *object) {
    // For Java objects, the ForeignObject deleter calls
    // polyglot_java_release_object (JNI DeleteGlobalRef) when the last
    // reference is released.
    if (!object) return;

    auto *fo = static_cast<ForeignObject *>(object);
    if (ForeignIsAlive(fo)) {
        ReleaseForeign(fo);
    }
}

void __ploy_dotnet_dispose(void *object) {
    // For .NET objects, the ForeignObject deleter calls
    // polyglot_dotnet_dispose / polyglot_dotnet_release_object when the
    // last reference is released.
    if (!object) return;

    auto *fo = static_cast<ForeignObject *>(object);
    if (ForeignIsAlive(fo)) {
        ReleaseForeign(fo);
    }
}

// ============================================================================
// Cross-language class extension / vtable registration
// ============================================================================

struct ExtensionEntry {
    const char *language{nullptr};
    const char *base_class{nullptr};
    const char *derived{nullptr};
};

static std::vector<ExtensionEntry> g_extensions;
static std::shared_mutex           g_extension_mutex;

void __ploy_extend_register(const char *language, const char *base_class,
                             const char *derived) {
    if (!language || !base_class || !derived) return;

    std::unique_lock<std::shared_mutex> lock(g_extension_mutex);

    // Duplicate the strings into GC-managed memory so they survive module unload.
    auto dup = [](const char *s) -> const char * {
        std::size_t len = std::strlen(s) + 1;
        char *buf = static_cast<char *>(polyglot_alloc(len));
        if (buf) std::memcpy(buf, s, len);
        return buf;
    };

    g_extensions.push_back(ExtensionEntry{
        dup(language),
        dup(base_class),
        dup(derived),
    });
}

std::size_t __ploy_extend_registry_count() {
    std::shared_lock<std::shared_mutex> lock(g_extension_mutex);
    return g_extensions.size();
}

const char *__ploy_extend_find_derived(const char *language,
                                       const char *base_class) {
    if (!language || !base_class) return nullptr;

    std::shared_lock<std::shared_mutex> lock(g_extension_mutex);
    for (const ExtensionEntry &entry : g_extensions) {
        if (!entry.language || !entry.base_class || !entry.derived) continue;
        if (std::strcmp(entry.language, language) == 0 &&
            std::strcmp(entry.base_class, base_class) == 0) {
            return entry.derived;
        }
    }
    return nullptr;
}

void __ploy_extend_reset_registry_for_tests() {
    std::unique_lock<std::shared_mutex> lock(g_extension_mutex);
    g_extensions.clear();
}

// ============================================================================
// String / memory conversion helpers
// ============================================================================

char *__ploy_rt_string_convert(const void *src, std::size_t len) {
    if (!src) return nullptr;

    const char *s = static_cast<const char *>(src);

    // If len == 0 compute length from a null-terminated source.
    if (len == 0) {
        len = std::strlen(s);
    }

    // Allocate a GC-managed buffer for the converted string.
    char *buf = static_cast<char *>(polyglot_alloc(len + 1));
    if (!buf) return nullptr;
    std::memcpy(buf, s, len);
    buf[len] = '\0';
    return buf;
}

void *__ploy_rt_memcpy(void *dst, const void *src, std::size_t size) {
    if (!dst || !src || size == 0) return dst;
    return std::memcpy(dst, src, size);
}

// ============================================================================
// Container conversion helpers
// ============================================================================

void *__ploy_rt_convert_tuple(void *tuple) {
    // Identity conversion for RuntimeTuple pointers that are already in the
    // canonical layout.  When the source and target languages use different
    // element sizes / padding this function would re-pack the data.  For now
    // we perform a deep copy so the caller owns the result independently.
    if (!tuple) return nullptr;

    auto *src = static_cast<RuntimeTuple *>(tuple);

    // Collect element sizes from offsets (approximate: size[i] = offset[i+1] - offset[i]).
    std::size_t n = src->num_elements;
    if (n == 0) return __ploy_rt_tuple_create(0, nullptr);

    auto *elem_sizes = static_cast<std::size_t *>(std::calloc(n, sizeof(std::size_t)));
    if (!elem_sizes) return nullptr;

    for (std::size_t i = 0; i < n; ++i) {
        if (i + 1 < n) {
            elem_sizes[i] = src->offsets[i + 1] - src->offsets[i];
        } else {
            // Last element: estimate from total allocation — not perfectly knowable
            // without explicit metadata.  Use 8 bytes as a safe upper bound.
            elem_sizes[i] = 8;
        }
    }

    void *dst = __ploy_rt_tuple_create(n, elem_sizes);
    if (dst) {
        auto *dt = static_cast<RuntimeTuple *>(dst);
        // Copy each element using the source offsets.
        for (std::size_t i = 0; i < n; ++i) {
            void *src_elem = static_cast<char *>(src->data) + src->offsets[i];
            void *dst_elem = static_cast<char *>(dt->data) + dt->offsets[i];
            std::memcpy(dst_elem, src_elem, elem_sizes[i]);
        }
    }

    std::free(elem_sizes);
    return dst;
}

void *__ploy_rt_dict_convert(void *dict) {
    // Deep-copy a RuntimeDict into a new instance.  In a cross-language
    // scenario this would also re-hash using the target language's hash
    // function; for now we use byte-level equality which is correct for
    // primitive key types.
    if (!dict) return nullptr;

    auto *src = static_cast<RuntimeDict *>(dict);
    void *dst = __ploy_rt_dict_create(src->key_size, src->value_size);
    if (!dst) return nullptr;

    // Iterate all occupied slots and re-insert entries.
    for (std::size_t i = 0; i < src->capacity; ++i) {
        const auto *slot_base = static_cast<const char *>(src->slots) + i * src->slot_stride;
        // SlotState is the first byte of each slot.
        const auto *st = reinterpret_cast<const std::uint8_t *>(slot_base);
        if (*st != static_cast<std::uint8_t>(SlotState::kOccupied)) continue;

        const void *kptr = slot_base + src->key_offset;
        const void *vptr = slot_base + src->value_offset;
        __ploy_rt_dict_insert(dst, kptr, vptr);
    }

    return dst;
}

void *__ploy_rt_convert_struct(void *src) {
    // The source is a contiguous block whose first sizeof(size_t) bytes hold
    // the total data size.  We deep-copy the entire block so the caller gets
    // an independent copy suitable for the target language's layout.
    if (!src) return nullptr;

    std::size_t total_size = *static_cast<std::size_t *>(src);
    if (total_size == 0) return nullptr;

    // The total_size field itself is part of the allocation.
    std::size_t alloc_size = sizeof(std::size_t) + total_size;
    void *dst = std::calloc(1, alloc_size);
    if (!dst) return nullptr;

    std::memcpy(dst, src, alloc_size);
    return dst;
}

}  // namespace polyglot::runtime::interop
