#!/usr/bin/env python3
"""Regenerate the checked-in ARM64 runtime words from reviewable assembly.

Requires clang with AArch64 assembler support only when regenerating; polyc
itself ships these words and never invokes clang. Reject any unresolved reloc.
"""
import argparse
from pathlib import Path
import struct
import subprocess
import tempfile
ROOT=Path(__file__).resolve().parents[1]

def extract_elf(path):
    b=path.read_bytes()
    assert b[:5]==b'\x7fELF\x02'
    shoff=struct.unpack_from('<Q',b,40)[0]
    ents,n,strings=struct.unpack_from('<HHH',b,58)
    sections=[struct.unpack_from('<IIQQQQIIQQ',b,shoff+i*ents) for i in range(n)]
    def data(i):
        s=sections[i];return b[s[4]:s[4]+s[5]]
    def name(tab,off):return tab[off:tab.index(0,off)].decode()
    names=data(strings)
    text=next(i for i,s in enumerate(sections) if name(names,s[0])=='.text')
    for s in sections:
        if s[1] in (4,9) and s[7]==text: assert s[5]==0, 'runtime must have no relocations'
    symbols=[]
    for i,s in enumerate(sections):
        if s[1]!=2:continue
        strings=data(s[6]);symtab=data(i)
        for off in range(0,len(symtab),s[9]):
            nm,info,other,sec,val,size=struct.unpack_from('<IBBHQQ',symtab,off)
            nm=name(strings,nm)
            if sec==text and nm.startswith('polyrt_'):symbols.append((nm,val))
    return data(text),sorted(symbols,key=lambda s:s[1])

def main():
    ap=argparse.ArgumentParser(description=__doc__);ap.add_argument('--check',action='store_true');ap.add_argument('--clang',default='clang');a=ap.parse_args()
    lines=['// Generated by scripts/generate_native_runtime.py; edit native/arm64_runtime.S.', '']
    with tempfile.TemporaryDirectory(prefix='poly-runtime-') as t:
        for os in ('darwin','linux'):
            obj=Path(t)/(os+'.o')
            cmd=[a.clang,'-target','aarch64-linux-gnu','-x','assembler-with-cpp','-c',str(ROOT/'runtime/src/libs/native/arm64_runtime.S'),'-o',str(obj)]
            if os=='darwin':cmd.append('-D__APPLE__=1')
            subprocess.run(cmd,check=True)
            code,symbols=extract_elf(obj)
            lines.append(f'static constexpr std::uint32_t kArm64_{os}[] = {{')
            words=struct.unpack('<'+'I'*(len(code)//4),code)
            for i in range(0,len(words),6):lines.append('  '+', '.join(f'0x{w:08x}u' for w in words[i:i+6])+',')
            lines += ['};',f'static const NativeFileRuntimeSymbol kArm64_{os}_symbols[] = {{']
            for i,(name,offset) in enumerate(symbols[:-1]):
                lines.append(f'  {{"{name}", {offset}, {symbols[i+1][1]-offset}}},')
            lines += ['};','']
    out=ROOT/'runtime/src/libs/native/arm64_runtime.inc';text='\n'.join(lines)
    if a.check: assert out.read_text()==text, 'generated runtime differs; regenerate'
    else:out.write_text(text)
if __name__=='__main__':main()
